### ISSUE TITLE
Serialize: Consder enabling OptHistory saving when .json serialization is not available

### ISSUE THREAD

**Issue by gkirgizov** [aimclub/GOLEM#110]
Description of the problem by @ZharkovKirill 

> Добрый день, позапускал эксперименты с обновленным големом. `OptHistory.save_current_results`  не работает в нашем случае. Ноды графа через json не серилизуются(pickle да).  Есть какие-нибудь механизмы для кастомизации дампа? Метод `to_csv` работает, могу в таком формате кинуть.

**Comment by YamLyubov** [comment]
Solved in #215
