### ISSUE TITLE
Serialize: Add light-weight OptHistory saving

### ISSUE THREAD

**Issue by gkirgizov** [aimclub/GOLEM#118]
Currently OptHistories can be very large objects, with a size > 1Gb e.g. for molecular search or any graphs with large state.

It's quite unmanagable if we just want to have, say, 10 trials and build comparison between 2 cases with 10 trials each.

So we need a light-weight history saving that doesn't save graphs, and stores only fitness & individuals id. Requirements are:
- being able to plot most of OptHistoryVizualizer plots
- being able to plot evolutionary history for FEDOT.Web

**Comment by nicl-nno** [comment]
А не будут ли такие 1Gb-истории хорошо сжиматься в zip?

**Comment by gkirgizov** [comment]
> А не будут ли такие 1Gb-истории хорошо сжиматься в zip?

Нужно проверить

**Comment by MorrisNein** [comment]
Можно отказаться от аргумента indent, чтобы сэкономить немного места.
