### ISSUE TITLE
Adaptive mutations bugs

### ISSUE THREAD

**Issue by MangaBoba** [aimclub/GOLEM#221]
For [0.3.3 release](https://github.com/aimclub/GOLEM/releases/tag/v0.3.3):

- [ ] 1. In case of _MutationAgentTypeEnum.bandit_, if some mutation [could not be applied](https://github.com/aimclub/GOLEM/blob/main/golem/core/optimisers/genetic/operators/mutation.py#L87) to whole population, [mutation operation](https://github.com/aimclub/GOLEM/blob/main/golem/core/optimisers/genetic/operators/reproduction.py#L84C53-L84C82) returns empty list, then [evaluation step](https://github.com/aimclub/GOLEM/blob/main/golem/core/optimisers/genetic/operators/reproduction.py#L85) [produces None](https://github.com/aimclub/GOLEM/blob/main/golem/core/optimisers/genetic/evaluation.py#L278). Described above leads to _TypeError: 'NoneType' object is not iterable_ on [collecting next population](https://github.com/aimclub/GOLEM/blob/main/golem/core/optimisers/genetic/operators/reproduction.py#L109).
- [x] 2. In case of _MutationAgentTypeEnum.neural_bandit_ (fixed in 6f0dcf686305686b3f787a41772667ba05e1df17):
```
   File "F:\GEFEST\.venv\lib\site-packages\golem\core\optimisers\adaptive\mab_agents\neural_contextual_mab_agent.py", line 17, in __init__
    super().__init__(actions=actions, n_jobs=n_jobs,
TypeError: __init__() missing 1 required positional argument: 'available_operations'
```

**Comment by maypink** [comment]
For [0.4.0](https://github.com/aimclub/GOLEM/issues/221) release
