### ISSUE TITLE
Tuner refactoring

### ISSUE THREAD

**Issue by valer1435** [aimclub/GOLEM#27]
Now tuner uses metrics that not compatible with composer metrics. Also it has a monolith structure.

What should be done:

- [x]  Union metrics for composer and tuner
- [x]  Make tuner more flexible using decomposition
- [x]  Implement self._objective as separate module 
- [x] Refactor view of model parameters. Now they become too complicated to store them into `dict` (see aimclub/FEDOT#862)

UPD (from @gkirgizov) Additional subtasks:

- [x] `HyperOpt.get_metric_value` seems to duplicate logic of PipelineObjectiveEvaluate that's concerned with how to validate the model -- so it's better to use it instead.
- [ ] Abstract Tuner to arbitrary Graphs.
   The only place where the specifics of Pipeline are required -- is for evaluation of objective. But, I think, currently this can be encapsualted with Objective/ObjectiveEvaluate classes.

Regarding 1st and 3rd points by Valera, possibly `Objective` class is useful here.

**Comment by gkirgizov** [comment]
closed by #21
