### ISSUE TITLE
Fix recursion errors in graph functions for cyclic graphs 

### ISSUE THREAD

**Issue by gkirgizov** [aimclub/GOLEM#29]
The problem is because of recursive traversals that break on cycles. The task is:
- Reproduce issue, write tests for graphs with loops
- solution is to rewrite recursion in a usual loop with stack.

Affected functions:
- [ ] in `graph_growth` the bug is sure
- [ ] `descriptive_id_recursive` must be checked
- [ ] `distance_to_primary_level`
- maybe more...

**Comment by nicl-nno** [comment]
Добавлю, что как-то Ярослав @staeros натыкался на ситуации, когда для "глубоких" графов (при этом довольно линейных по структуре) построение descriptive_id занимало относительно много времени

**Comment by gkirgizov** [comment]
Also breaks vizualisations: https://github.com/aimclub/GOLEM/pull/75#discussion_r1154394538

**Comment by gkirgizov** [comment]
Fixed by #137
