### ISSUE TITLE
Review literature on used Mutation & Crossover operators for graphs

### ISSUE THREAD

**Issue by gkirgizov** [aimclub/GOLEM#59]
Motivation: universal graph optimization that could work for many different domains requires mutations that are effective across many tasks. To do that it's required to conduct an initial overview of used mutations.

- Find papers that use evolution of some graphs.
- Describe what kinds of structures are optimized (chemical, robotic, etc.) and what are the constraints for them.
- Describe what mutations are effective for these graphs, and why (if authors say it)
 
Result is the list of these findings.

After this it will be possible to extract commonalities and understand what mutations we would need for universality

**Comment by gkirgizov** [comment]
@YamLyubov Добавь сюа ссылку на свою таблицу с результатами, и можно закрыть issue

**Comment by YamLyubov** [comment]
Результаты обзора https://docs.google.com/spreadsheets/d/1WAeuDTKqhS2_44895QC-DjmucxJRq6LydYxBqBaEurg/edit#gid=0
