### ISSUE TITLE
Implement support for surrogate-assisted optimisation

### ISSUE THREAD

**Issue by nicl-nno** [aimclub/GOLEM#79]
As a part of MetaAutoML project, the feature of surrogate-assisted evolution is required in FEDOT optmiser.

As a first step, the simpe surrogate scheme can be implemened - e.g. surrogate estimation of fitness before selection.

I think experience of @valer1435 and @maypink from previous projects can be useful. Also, surrogates can be useful to improve 
the convergence of sensitivity analysis.

Related paper: https://arxiv.org/pdf/2206.01520.pdf

**Comment by gkirgizov** [comment]
@valer1435 , закрыто ли после твоего PR #82 ?

**Comment by maypink** [comment]
@valer1435 все еще вопросы без ответов. Закрывать?
